---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/12 12:07
---


--CategoryBitmask
local HERO = 1                  --0001
local HERO_BULLET = 2           --0010
local ENEMY = 4                 --0100
local ENEMY_BULLET = 8          --1000

--ContactBitmask
local HERO_CONTACT = 12         --1100
local HERO_BULLET_CONTACT = 4   --0100
local ENEMY_CONTACT = 3         --0011
local ENEMY_BULLET_CONTACT = 1  --0001

local common = require("common")
local Tank = require("sprite.Tank")

local EnemyTank = class("EnemyTank", Tank)

function EnemyTank:ctor()

    self.super:ctor()
    --添加精灵图片
    local spriteFrame = cc.SpriteFrameCache:getInstance()
    spriteFrame:addSpriteFrames("qing_tank.plist")
    self:setSpriteFrame("tank_enemy_1.png")

    local function onNodeEvent(tag)
        if tag == "enter" then
            self:onEnter()
        elseif tag == "enterTransitionFinish" then
            self:onEnterTransitionFinish()
        elseif tag == "exit" then
            self:onExit()
        end
    end

    self:registerScriptHandler(onNodeEvent)
end

function EnemyTank:onEnter()
    --渲染移动动画
    self:renderMoveAnimation(ENEMY)
    --添加物理刚体
    self:renderPhysicsBody(ENEMY, ENEMY_CONTACT)
    self:renderBoomAnimation()
end

function EnemyTank:onEnterTransitionFinish()
    self:randomMove()
end

function EnemyTank:randomMove()
    self:tankStopMove()
    local direction = common.getRandNum(1, 4)
    --print("direstion  "..direction)
    self:tankMove(direction)
    --print("test  "..self.movingTime)
    local nextMoveTime = common.getRandNum(0, math.ceil(self.movingTime)) + math.random()
    --print("nextMoveTime   "..nextMoveTime)
    local function nextMove()
        self:randomMove()
        --cclog("already calm down")
    end

    performWithDelay(self:getParent(), nextMove, nextMoveTime)
end

return EnemyTank