---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/8 11:32
---

local size = cc.Director:getInstance():getWinSize()

local MissionLayer = class("MissionLayer", function()
    return cc.Layer:create()
end)

function MissionLayer:ctor()

    cclog("mission layer init")

    local backGroundColor = cc.LayerColor:create(cc.c3b(224, 224, 224))
    self:addChild(backGroundColor)

    local label = cc.Label:createWithSystemFont("Mission One", "Arial", 48)
    label:setPosition(cc.p(size.width / 2, size.height / 2))
    label:setTextColor(cc.c4b(0, 0, 0, 124))
    self:addChild(label)

    local toPlayScene = function()
        local director = cc.Director:getInstance()
        local scene = require("scene.PlayScene")
        local playScene = scene:create()

        director:replaceScene(playScene)
    end
    local Timer = cc.Director:getInstance():getScheduler():scheduleScriptFunc(toPlayScene, 2.5, false)

    --layer:scheduleOnce(schedule_selsector(missionScene:toPlayScene()),5.0)

    local function onNodeEvent(tag)
        if tag == "exit" then
            --layer:unscheduleUpdate()
            cc.Director:getInstance():getScheduler():unscheduleScriptEntry(Timer)
        end
    end

    self:registerScriptHandler(onNodeEvent)

end

return MissionLayer