---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/8 11:41
---

local size = cc.Director:getInstance():getWinSize()

local playGroundLayer = class("playGroundLayer", function()
    return cc.Layer:create()
end)

function playGroundLayer:create()
    cclog("play groud layer init")
    local layer = cc.Layer:create()

    cclog("spriteTank init")

    tank = cc.Sprite:create("tank.png", cc.rect(61, 608, 61, 61))
    tank:setAnchorPoint(cc.p(0, 0))
    tank:setPosition(cc.p(size.width / 2, size.height / 2))
    layer:addChild(tank, 0)

    return layer
end

return playGroundLayer