---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/8 11:41
---
local common = require("common")
local Tank = require("sprite.Tank")
local size = cc.Director:getInstance():getWinSize()

local playGroundLayer = class("playGroundLayer", function()
    return cc.Layer:create()
end)

function playGroundLayer:ctor()
    cclog("play ground layer init sprite")

    local tank = Tank:create("tank_stay_1.png")
    tank:setTag(1)
    tank:setPosition(cc.p(size.width / 2, size.height / 2))
    self:addChild(tank, 0, 1)

    local edgeNode = cc.Node:create()
    edgeNode:setPosition(size.width / 2, size.height / 2)
    edgeNode:setPhysicsBody(
            cc.PhysicsBody:createEdgeBox(cc.size(size.height, size.height),
                    cc.PhysicsMaterial(0.1, 1.0, 0.0)
            ))
    self:addChild(edgeNode)

    local function onNodeEvent(tag)
        if tag == "enter" then
            cclog("in enter")
            self:onEnter()
        end
    end

    self:registerScriptHandler(onNodeEvent)


    --生成5个坦克测试碰撞，后期删除
    cclog("test physic")
    local spriteFrame = cc.SpriteFrameCache:getInstance()
    spriteFrame:addSpriteFrames("tank.plist")
    for i = 1, 5 do

        local sprite = cc.Sprite:createWithSpriteFrameName("tank_enemy_2.png")
        sprite:setTag(3)
        local physicsBody = cc.PhysicsBody:createBox(sprite:getContentSize())
        physicsBody:setGravityEnable(false)
        physicsBody:setVelocity(cc.p(common.getRandNum(-1000, 1000), common.getRandNum(-1000, 1000)))
        physicsBody:setTag(0x80)
        sprite:setPosition(cc.p(
                common.getRandNum(30 + (size.width - size.height) / 2, size.width - 30 - (size.width - size.height) / 2),
                common.getRandNum(30, size.height - 30)
        ))
        sprite:addComponent(physicsBody)

        self:addChild(sprite)
    end

end

function playGroundLayer:operateByTag(tag)
    if tag ~= 5 then
        self:getChildByTag(1):tankMove(tag)
    else
        if self:getChildByTag(1):tankFire() then
            local function fireCalmDown()
                self:getChildByTag(1):setFireCalmDown()
                --cclog("already calm down")
            end
            performWithDelay(self, fireCalmDown, 0.5)
        end
    end

end

--使英雄停止移动
function playGroundLayer:heroStopMove()
    self:getChildByTag(1):tankStopMove()
end

--获得英雄方向
function playGroundLayer:getHeroDirection()
    return self:getChildByTag(1):getCurrentDirection()
end

function playGroundLayer:onEnter()
    --初始化物理引擎
    cclog('init contact')

    local function onContactBegin(contact)
        cclog("in contact")
        local spriteA = contact:getShapeA():getBody():getNode()
        local spriteB = contact:getShapeB():getBody():getNode()
        print(spriteA:getTag() .. '    ' .. spriteB:getTag())
        if ((spriteA:getTag() == 2) and (spriteB:getTag() == 1))
                or
                ((spriteA:getTag() == 1) and (spriteB:getTag() == 2)) then
            cclog("hit the mark!!")


        end
    end

    local listener = cc.EventListenerPhysicsContact:create()
    listener:registerScriptHandler(onContactBegin, cc.Handler.EVENT_PHYSICS_CONTACT_BEGIN)

    local evetDispatch = cc.Director:getInstance():getEventDispatcher()
    evetDispatch:addEventListenerWithSceneGraphPriority(listener, self)

end

return playGroundLayer