---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/8 11:42
---

local playPadLayer = class("playGroundLayer", function()
    return cc.Layer:create()
end)

local initButton = function(targert)

    local spriteFrame = cc.SpriteFrameCache:getInstance()
    spriteFrame:addSpriteFrames("arrows.plist")

    --1234 上右下左

    local buttonUp = cc.Sprite:createWithSpriteFrameName("arrow_up_64.png")
    buttonUp:setPosition(cc.p(150, 250))
    targert:addChild(buttonUp, 0, 1)

    local buttonRight = cc.Sprite:createWithSpriteFrameName("arrow_right_64.png")
    buttonRight:setPosition(cc.p(250, 150))
    targert:addChild(buttonRight, 0, 2)

    local buttonDown = cc.Sprite:createWithSpriteFrameName("arrow_down_64.png")
    buttonDown:setPosition(cc.p(150, 50))
    targert:addChild(buttonDown, 0, 3)

    local buttonLeft = cc.Sprite:createWithSpriteFrameName("arrow_left_64.png")
    buttonLeft:setPosition(cc.p(50, 150))
    targert:addChild(buttonLeft, 0, 4)

end

local initOnTouchEvent = function(target)

    --定义四个按钮区域
    local rectLeft = cc.rect(0, 100, 100, 100)
    local rectRight = cc.rect(200, 100, 100, 100)
    local rectUp = cc.rect(100, 200, 100, 100)
    local rectDown = cc.rect(100, 0, 100, 100)

    local function onTouchBegan(touch)
        cclog("on touch")
        local locationInTouch = touch:getLocation()

        if cc.rectContainsPoint(rectUp, locationInTouch) then
            cclog("up")
            target:getChildByTag(1):setOpacity(180)
            target.groundLayer:heroMove("up")
        elseif cc.rectContainsPoint(rectRight, locationInTouch) then
            cclog("right")
            target:getChildByTag(2):setOpacity(180)
            target.groundLayer:heroMove("right")
        elseif cc.rectContainsPoint(rectDown, locationInTouch) then
            cclog("down")
            target:getChildByTag(3):setOpacity(180)
            target.groundLayer:heroMove("down")
        elseif cc.rectContainsPoint(rectLeft, locationInTouch) then
            cclog("left")
            target:getChildByTag(4):setOpacity(180)
            target.groundLayer:heroMove("left")
        end
        return true
    end

    local resetOpacity = function()
        for i = 1, 4 do
            target:getChildByTag(i):setOpacity(255)
        end
    end

    local function onTouchMoved(touch)
        cclog("on move")
        local locationInTouch = touch:getLocation()

        local function setOpacityBatchly(tag)
            --统一设置四个按钮的透明度，后期可由groundLayer获取移动标志以处理透明度
            for i = 1, 4 do
                if i == tag then
                    target:getChildByTag(i):setOpacity(180)
                else
                    target:getChildByTag(i):setOpacity(255)
                end

            end
        end

        if cc.rectContainsPoint(rectUp, locationInTouch) then
            cclog("move in up")
            setOpacityBatchly(1)
        elseif cc.rectContainsPoint(rectRight, locationInTouch) then
            cclog("move in right")
            setOpacityBatchly(2)
        elseif cc.rectContainsPoint(rectDown, locationInTouch) then
            cclog("move in down")
            setOpacityBatchly(3)
        elseif cc.rectContainsPoint(rectLeft, locationInTouch) then
            cclog("move in left")
            setOpacityBatchly(4)
        else
            resetOpacity()
        end
    end

    local function onTouchEnded()
        --统一设置所有按钮透明度恢复，后期可由groundLayer获取移动标志以处理透明度
        resetOpacity()
    end

    local listener = cc.EventListenerTouchOneByOne:create()
    listener:registerScriptHandler(onTouchBegan, cc.Handler.EVENT_TOUCH_BEGAN)
    listener:registerScriptHandler(onTouchMoved, cc.Handler.EVENT_TOUCH_MOVED)
    listener:registerScriptHandler(onTouchEnded, cc.Handler.EVENT_TOUCH_ENDED)

    local evetDispatch = cc.Director:getInstance():getEventDispatcher()
    evetDispatch:addEventListenerWithSceneGraphPriority(listener, target)


end

function playPadLayer:create()
    cclog("gamepad layer init")
    local layer = playPadLayer:new()

    initButton(layer)

    initOnTouchEvent(layer)

    return layer
end

return playPadLayer