---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/6 17:13
---


local MenuScene = class("MenuScene", function()
    return cc.Scene:create()
end)

function MenuScene:ctor()
    cclog("menuScene init")
    local scene = self:new()
    local layer = require("layer.MenuLayer")
    local menuLayer = layer:create()
    scene:addChild(menuLayer)
    return scene
end

return MenuScene