---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/6 17:13
---

local size = cc.Director:getInstance():getWinSize()

local menuScene = class("menuScene", function()
    return cc.Scene:create()
end)

function menuScene:create()
    cclog("menuScene init")
    local scene = menuScene:new()
    local layer = require("layer.menuLayer")
    local menuLayer = layer:create()
    scene:addChild(menuLayer)
    return scene
end

function menuScene:ctor()
end

return menuScene