---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/6 12:47
---


local MissionScene = class("MissionScene", function()
    return cc.Scene:create()
end)

function MissionScene:ctor()
    cclog("missionScene init")
    local scene = self:new()
    local layer = require("layer.MissionLayer")
    local missionLayer = layer:create()
    scene:addChild(missionLayer)
    return scene
end

return MissionScene