---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/6 13:57
---


local PlayGroundLayer = require("layer.PlayGroundLayer")
local PlayPadLayer = require("layer.PlayPadLayer")

local PlayScene = class("PlayScene", function()
    return cc.Scene:createWithPhysics()
end)

function PlayScene:ctor()
    cclog("playScene init")
    local groundLayer = PlayGroundLayer:create()
    self:addChild(groundLayer, 0, 1)

    local padLayer = PlayPadLayer:create()
    self:addChild(padLayer, 1, 2)

    --绑定游戏层为操作层的成员
    padLayer.groundLayer = groundLayer

end

return PlayScene