---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/6 13:57
---


local size = cc.Director:getInstance():getWinSize()

local playScene = class("playScene", function()
    return cc.Scene:create()
end)

function playScene:create()
    cclog("playScene init")
    local scene = playScene:new()

    local playGroundLayer = require("layer.playGroundLayer")
    local groundLayer = playGroundLayer:create()
    scene:addChild(groundLayer, 0, 1)

    local playPadLayer = require("layer.playPadLayer")
    local padLayer = playPadLayer:create()
    scene:addChild(padLayer, 1, 2)

    --绑定游戏层为操作层的成员
    padLayer.groundLayer = groundLayer

    return scene
end

function playScene:ctor()

end


--添加坦克动画




local function tankRun(sprite)

    local spriteFrame = cc.SpriteFrameCache:getInstance()
    spriteFrame:addSpriteFrames("tank.plist")

    local animation = cc.Animation:create()
    for i = 1, 2 do
        local frameName = string.format("tank_move_%d.png", i)
        cclog("frameName = %s", frameName)
        local tankFrame = spriteFrame:getSpriteFrameByName(frameName)
        animation:addSpriteFrame(tankFrame)
    end

    animation:setDelayPerUnit(0.15)
    animation:setRestoreOriginalFrame(true)
    local action = cc.Animate:create(animation)
    sprite:runAction(cc.RepeatForever:create(action))
end

local function tankStopRun(sprite)
    sprite:stopAllActions()
end


return playScene