---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/6 13:57
---


local PlayScene = class("PlayScene", function()
    return cc.Scene:create()
end)

function PlayScene:ctor()
    cclog("playScene init")

    local playGroundLayer = require("layer.PlayGroundLayer")
    local groundLayer = playGroundLayer:create()
    self:addChild(groundLayer, 0, 1)

    local playPadLayer = require("layer.PlayPadLayer")
    local padLayer = playPadLayer:create()
    self:addChild(padLayer, 1, 2)

    --绑定游戏层为操作层的成员
    padLayer.groundLayer = groundLayer

end

return PlayScene