---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangsen.
--- DateTime: 2018/8/9 20:29
---

math.randomseed(tonumber(tostring(os.time()):reverse():sub(1, 7)))

local common = {}

common.polarToRightAngle = function(x, y, length, radian)
    return cc.p(
            x + length * math.sin(math.rad(90 * (radian - 1))),
            y + length * math.cos(math.rad(90 * (radian - 1))))

end

common.initMoveTo = function(direction, timePerPixel, originX, originY, obligate)
    local time
    local destination
    local size = cc.Director:getInstance():getWinSize()

    local minX = (size.width - size.height) / 2 + obligate
    local maxX = size.width - minX
    local minY = obligate
    local maxY = size.height - minY

    if direction == 1 then
        time = timePerPixel * (maxY - originY)
        destination = cc.p(originX, maxY)
    elseif direction == 2 then
        time = timePerPixel * (maxX - originX)
        destination = cc.p(maxX, originY)
    elseif direction == 3 then
        time = timePerPixel * (originY - minY)
        destination = cc.p(originX, minY)
    elseif direction == 4 then
        time = timePerPixel * (originX - minX)
        destination = cc.p(minX, originY)
    end
    return time, destination
end

common.getRandNum = function(min, max)
    return math.random(min, max)
end


return common